<a href="https://colab.research.google.com/github/Vyshnavi262007/Assignment-3-AIML/blob/main/Customer_Segmentation_Using_K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [3]:
import pandas as pd

data = {
    'Annual Income':[15,16,17,18,19,40,42,44,46,48,70,72,74,76,78],
    'Spending Score':[39,41,35,50,55,60,62,65,70,72,20,22,25,27,30]
}

customers = pd.DataFrame(data)

customers.head()

   Annual Income  Spending Score
0             15              39
1             16              41
2             17              35
3             18              50
4             19              55

In [4]:
X = customers[['Annual Income','Spending Score']]

kmeans = KMeans(n_clusters=3, random_state=42)

clusters = kmeans.fit_predict(X)

customers['Cluster'] = clusters

customers.head()

   Annual Income  Spending Score  Cluster
0             15              39        2
1             16              41        2
2             17              35        2
3             18              50        2
4             19              55        2

In [5]:
score = silhouette_score(X, clusters)

print("Silhouette Score:", score)

Silhouette Score: 0.7814477354645387